### ISSUE TITLE
pip3 run issue on some systems

### ISSUE THREAD

**Issue by Warfields** [ColoradoSchoolOfMines/visplay#4]
running "pip3 install -e . --user" works but running "visplay" afterwords blows up resulting in:

[warfield@csm-wl-dhcp-230-65 visplay]$ visplay 
Traceback (most recent call last):
  File "/home/warfield/.local/bin/visplay", line 11, in <module>
    load_entry_point('visplay', 'console_scripts', 'visplay')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2749, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2402, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'visplay.__main__'

Possible fix, change line 24 of setup.py:
From: 'visplay=visplay.__main__:main',
To    : 'visplay=visplay:main',

OS: Fedora 27

**Comment by Warfields** [comment]
The new installation procedure seems to have fixed this btw

**Comment by robozman** [comment]
Awesome. Hopefully this is fixed for good.
